// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZAD_WEB_2b.Models.Databse;

namespace ZAD_WEB_2b.Migrations
{
    [DbContext(typeof(InfoDbContext))]
    [Migration("20230127223946_prvni migrace")]
    partial class prvnimigrace
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("ZAD_WEB_2b.Models.Entities.Informace", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DatumVytvoreni")
                        .HasColumnType("longtext");

                    b.Property<string>("Detail")
                        .HasColumnType("longtext");

                    b.Property<string>("Nazev")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Informace");
                });
#pragma warning restore 612, 618
        }
    }
}
